# Objectives

After completing this lab you will be able to:

 - Use training, testing and cross validation to improve the performance of the dataset. 
 - Identify the point of overfitting of a model
 - Use Ridge Regression to identify the change in performance of a model based on its hyperparameters
 - Use Grid Search to identify the best performing model using different hyperparameters

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import requests

In [2]:
def download (url, fileName):
    response  = requests.get(url)
    if (response.status_code == 200):
        with open( fileName, "wb") as f:
            f.write(response.content)

In [3]:
filepath = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-Coursera/laptop_pricing_dataset_mod2.csv'

In [5]:
download( filepath, "Laptop_Evaluation.csv")
file_Name = 'Laptop_Evaluation.csv'

In [6]:
df = pd.read_csv(file_Name)
df.head()

,Unnamed: 0.1,Unnamed: 0,Manufacturer,Category,GPU,OS,CPU_core,Screen_Size_inch,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_pounds,Price,Price-binned,Screen-Full_HD,Screen-IPS_panel
0,0,0,Acer,4,2,1,5,14.0,0.551724,8,256,3.52800,978,Low,0,1
1,1,1,Dell,3,1,1,3,15.6,0.689655,4,256,4.85100,634,Low,1,0
2,2,2,Dell,3,1,1,7,15.6,0.931034,8,256,4.85100,946,Low,1,0
3,3,3,Dell,4,2,1,5,13.3,0.551724,8,128,2.69010,1244,Low,0,1
4,4,4,HP,4,2,1,7,15.6,0.620690,8,256,4.21155,837,Low,1,0

In [10]:
# remove first two columns 
df = df.drop(["Unnamed: 0.1", "Unnamed: 0"], axis=1)
df.head()

,Manufacturer,Category,GPU,OS,CPU_core,Screen_Size_inch,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_pounds,Price,Price-binned,Screen-Full_HD,Screen-IPS_panel
0,Acer,4,2,1,5,14.0,0.551724,8,256,3.52800,978,Low,0,1
1,Dell,3,1,1,3,15.6,0.689655,4,256,4.85100,634,Low,1,0
2,Dell,3,1,1,7,15.6,0.931034,8,256,4.85100,946,Low,1,0
3,Dell,4,2,1,5,13.3,0.551724,8,128,2.69010,1244,Low,0,1
4,HP,4,2,1,7,15.6,0.620690,8,256,4.21155,837,Low,1,0

# Task 1 : Using Cross validation to improve the model

Divide the dataset into x_data and y_data parameters. Here y_data is the "Price" attribute, and x_data has all other attributes in the data set.

In [15]:
y_data = df['Price']
x_data = df.drop(['Price'], axis=1)

print("x_data :")
print(x_data.head(5))

print("\ny_data :")
print(y_data.head(5))

x_data :
  Manufacturer  Category  GPU  OS  CPU_core  Screen_Size_inch  CPU_frequency  \
0         Acer         4    2   1         5              14.0       0.551724
1         Dell         3    1   1         3              15.6       0.689655
2         Dell         3    1   1         7              15.6       0.931034
3         Dell         4    2   1         5              13.3       0.551724
4           HP         4    2   1         7              15.6       0.620690

   RAM_GB  Storage_GB_SSD  Weight_pounds Price-binned  Screen-Full_HD  \
0       8             256        3.52800          Low               0
1       4             256        4.85100          Low               1
2       8             256        4.85100          Low               1
3       8             128        2.69010          Low               0
4       8             256        4.21155          Low               1

   Screen-IPS_panel
0                 1
1                 0
2                 0
3                 1
4                 0

y_data :
0     978
1     634
2     946
3    1244
4     837
Name: Price, dtype: int64

Split the data set into training and testing subests such that you reserve 10% of the data set for testing purposes.

In [17]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size= 0.1, random_state=1)
print("Print number of training samples: ", x_train.shape[0])
print("Print number of test samples: ", x_test.shape[0])

Print number of training samples:  214
Print number of test samples:  24